class EvenFibs

	def sum_even_fibs(max)
		total, hi, lo = 0, 1, 0
		until hi > max
			lo, hi = hi, (hi + 1)			
			total += hi if hi.even?
		end
		total
	end

end

fibos = EvenFibs.new
puts fibos.sum_even_fibs(4000000)




# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.